# Generated by Django 5.1.4 on 2025-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionruns',
            name='run_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
