# Generated by Django 5.1.4 on 2024-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0002_block_grower_ranch_delete_examplemodel_block_ranch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avgCtnPrice', models.FloatField(default=0)),
                ('stdCtnCost', models.FloatField(default=0)),
                ('pricePerPound', models.FloatField(default=0)),
                ('standardCtnWeight', models.FloatField(default=0)),
                ('packingCharge', models.FloatField(default=0)),
                ('profitPerBag', models.FloatField(default=0, null=True)),
                ('promo', models.FloatField(default=0)),
            ],
        ),
    ]
