# Generated by Django 5.1.4 on 2025-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0002_alter_productionruns_run_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='planted_variety',
            new_name='crop',
        ),
        migrations.RemoveField(
            model_name='block',
            name='planted_commodity',
        ),
        migrations.AddField(
            model_name='block',
            name='krpc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='row_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='tree_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='avgCtnPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='packingCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pricePerPound',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='profitPerBag',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='promo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='standardCtnWeight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='stdCtnCost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
