# Generated by Django 5.1.4 on 2025-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0004_remove_block_gib_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='varieties',
            name='name',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='varieties',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
