# Generated by Django 5.1.4 on 2024-12-10 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0004_remove_block_crop_type_block_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedHarvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('planned_bins', models.IntegerField(default=0)),
                ('contractor', models.CharField(max_length=50, null=True)),
                ('harvesting_rate', models.FloatField(null=True)),
                ('hauler', models.CharField(max_length=50, null=True)),
                ('hauling_rate', models.FloatField(null=True)),
                ('pool_id', models.CharField(max_length=10)),
                ('harvest_date', models.DateField()),
                ('grower_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_harvests', to='grower_portal.block')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRuns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bins', models.IntegerField(default=0)),
                ('grower_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='grower_portal.block')),
            ],
        ),
        migrations.CreateModel(
            name='Receivings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receipt_id', models.CharField(max_length=20)),
                ('qty_received', models.IntegerField()),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Harvest', to='grower_portal.plannedharvest')),
            ],
        ),
    ]
