# Generated by Django 5.1.4 on 2025-04-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0005_remove_commodity_name_remove_varieties_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='crop',
            new_name='variety',
        ),
    ]
