# Generated by Django 5.1.4 on 2024-12-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0005_plannedharvest_productionruns_receivings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionruns',
            name='packout',
            field=models.FileField(null=True, upload_to='packouts/'),
        ),
        migrations.AddField(
            model_name='productionruns',
            name='qc_report',
            field=models.FileField(null=True, upload_to='qc_reports/'),
        ),
        migrations.AddField(
            model_name='productionruns',
            name='sizer_report',
            field=models.FileField(null=True, upload_to='sizer_reports/'),
        ),
    ]
