# Generated by Django 5.1.4 on 2024-12-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0006_productionruns_packout_productionruns_qc_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='gib_applied',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Varieties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='grower_portal.commodity')),
            ],
        ),
    ]
