# Generated by Django 5.1.4 on 2025-04-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0006_rename_crop_block_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionruns',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SizerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_JSON', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('process_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batchid', to='grower_portal.productionruns')),
            ],
        ),
    ]
