# Generated by Django 5.1.4 on 2025-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0007_productionruns_batch_id_sizerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionruns',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionruns',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
