# Generated by Django 5.1.4 on 2024-12-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0007_block_gib_applied_varieties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='crop',
            new_name='planted_commodity',
        ),
        migrations.AddField(
            model_name='block',
            name='planted_variety',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='variety', to='grower_portal.varieties'),
            preserve_default=False,
        ),
    ]
