# Generated by Django 5.1.4 on 2025-04-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0008_productionruns_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizerreport',
            name='process_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sizer_data', to='grower_portal.productionruns'),
        ),
        migrations.AlterField(
            model_name='sizerreport',
            name='raw_JSON',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
