# Generated by Django 5.1.4 on 2024-12-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0008_rename_crop_block_planted_commodity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborContractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_contact_name', models.CharField(max_length=50)),
                ('primary_contact_phone', models.IntegerField(null=True)),
                ('office_phone', models.IntegerField(null=True)),
                ('mailing_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckingContractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_contact_name', models.CharField(max_length=50)),
                ('primary_contact_phone', models.IntegerField(null=True)),
                ('office_phone', models.IntegerField(null=True)),
                ('mailing_address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
