# Generated by Django 5.1.4 on 2024-12-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0009_laborcontractors_truckingcontractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedharvest',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_contractors', to='grower_portal.laborcontractors'),
        ),
        migrations.AlterField(
            model_name='plannedharvest',
            name='hauler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucking_company', to='grower_portal.truckingcontractors'),
        ),
    ]
