# Generated by Django 5.1.4 on 2024-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0010_alter_plannedharvest_contractor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grower',
            old_name='contact_email',
            new_name='grower_contact_email',
        ),
        migrations.RenameField(
            model_name='grower',
            old_name='contact_phone',
            new_name='grower_contact_phone',
        ),
        migrations.AddField(
            model_name='grower',
            name='contract',
            field=models.FileField(null=True, upload_to='./grower_contracts'),
        ),
        migrations.AddField(
            model_name='grower',
            name='grower_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grower',
            name='property_manager_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='property_manager_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='property_manger_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
