# Generated by Django 5.1.4 on 2024-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0011_rename_contact_email_grower_grower_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='grower_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
