# Generated by Django 5.1.4 on 2024-12-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0013_folder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='grower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='grower_portal.grower'),
            preserve_default=False,
        ),
    ]
