# Generated by Django 5.1.4 on 2025-01-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0014_folder_grower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedharvest',
            name='name',
        ),
        migrations.AddField(
            model_name='plannedharvest',
            name='notes_general',
            field=models.TextField(blank=True, null=True),
        ),
    ]
