# Generated by Django 5.1.4 on 2025-01-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0016_alter_block_name_pools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedharvest',
            name='pool_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_pool', to='grower_portal.pools'),
        ),
    ]
