# Generated by Django 5.1.4 on 2025-01-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0017_alter_plannedharvest_pool_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedharvest',
            old_name='pool_id',
            new_name='pool',
        ),
    ]
