# Generated by Django 5.1.4 on 2025-01-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0018_rename_pool_id_plannedharvest_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldContractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_contact_name', models.CharField(max_length=50)),
                ('primary_contact_phone', models.IntegerField(null=True)),
                ('office_phone', models.IntegerField(null=True)),
                ('mailing_address', models.CharField(max_length=100, null=True)),
                ('provides_trucking', models.BooleanField(blank=True, null=True)),
                ('provides_picking', models.BooleanField(null=True)),
                ('provides_forklift', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plannedharvest',
            name='forklift_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plannedharvest',
            name='forklift_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forklift_contractor', to='grower_portal.fieldcontractors'),
        ),
        migrations.AlterField(
            model_name='plannedharvest',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_contractors', to='grower_portal.fieldcontractors'),
        ),
        migrations.AlterField(
            model_name='plannedharvest',
            name='hauler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucking_company', to='grower_portal.fieldcontractors'),
        ),
    ]
