# Generated by Django 5.1.4 on 2025-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0019_fieldcontractors_plannedharvest_forklift_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedharvest',
            name='packer',
            field=models.CharField(default='CF', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='plannedharvest',
            name='receiver',
            field=models.CharField(default='CF', max_length=30, null=True),
        ),
    ]
