# Generated by Django 5.1.4 on 2025-01-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0020_plannedharvest_packer_plannedharvest_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedharvest',
            old_name='packer',
            new_name='deliver_to',
        ),
        migrations.RenameField(
            model_name='plannedharvest',
            old_name='receiver',
            new_name='packed_by',
        ),
    ]
