# Generated by Django 5.1.4 on 2025-01-09 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0021_rename_packer_plannedharvest_deliver_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestPlansDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('estimated_bins', models.IntegerField()),
                ('harvest_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='grower_portal.plannedharvest')),
            ],
        ),
    ]
