# Generated by Django 5.1.4 on 2025-01-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0022_harvestplansdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedharvest',
            name='harvest_date',
        ),
    ]
