# Generated by Django 5.1.4 on 2025-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0024_receivings_date_alter_receivings_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivings',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
