# Generated by Django 5.1.4 on 2025-01-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0025_receivings_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedharvest',
            name='planned_bins',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receivings',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
