# Generated by Django 5.1.4 on 2025-02-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0026_alter_plannedharvest_planned_bins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='planted_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tocommodity', to='grower_portal.commodity'),
        ),
        migrations.AlterField(
            model_name='block',
            name='planted_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovariety', to='grower_portal.varieties'),
        ),
        migrations.AlterField(
            model_name='block',
            name='ranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toranch', to='grower_portal.ranch'),
        ),
        migrations.AlterField(
            model_name='pools',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooltocommodity', to='grower_portal.commodity'),
        ),
        migrations.AlterField(
            model_name='ranch',
            name='grower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='togrower', to='grower_portal.grower'),
        ),
        migrations.AlterField(
            model_name='varieties',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietytocommodity', to='grower_portal.commodity'),
        ),
    ]
