# Generated by Django 5.1.4 on 2025-03-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0027_alter_block_planted_commodity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionruns',
            name='name',
        ),
        migrations.AddField(
            model_name='productionruns',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionruns',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_pool', to='grower_portal.pools'),
        ),
        migrations.AddField(
            model_name='productionruns',
            name='run_date',
            field=models.DateField(null=True),
        ),
    ]
