# Generated by Django 5.1.4 on 2025-03-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0029_alter_block_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionruns',
            name='packout',
        ),
        migrations.RemoveField(
            model_name='productionruns',
            name='qc_report',
        ),
        migrations.RemoveField(
            model_name='productionruns',
            name='sizer_report',
        ),
    ]
