# Generated by Django 5.1.4 on 2025-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0030_remove_productionruns_packout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionruns',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionruns',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
