# Generated by Django 5.1.4 on 2025-03-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0031_productionruns_notes_alter_productionruns_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionruns',
            name='row_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
