# Generated by Django 5.1.4 on 2025-03-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0032_productionruns_row_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
