# Generated by Django 5.1.4 on 2025-03-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0033_remove_block_id_alter_block_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionruns',
            name='pool',
            field=models.CharField(blank=True, null=True),
        ),
    ]
