# Generated by Django 5.1.4 on 2024-12-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
