# Generated by Django 5.1.4 on 2024-12-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0003_alter_orders_color_id_alter_orders_commodity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
