# Generated by Django 5.1.4 on 2024-12-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0004_alter_orders_order_quantity_alter_orders_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sales_order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ship_to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
