# Generated by Django 5.1.4 on 2024-12-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0005_alter_orders_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.BigIntegerField(blank=True, null=True)),
                ('on_hand_quantity', models.FloatField(blank=True, null=True)),
                ('import_id', models.BigIntegerField(blank=True, null=True)),
                ('grade_id', models.TextField(blank=True, null=True)),
                ('variety_id', models.TextField(blank=True, null=True)),
                ('commodity_id', models.TextField(blank=True, null=True)),
                ('first_receive_date', models.TextField(blank=True, null=True)),
                ('warehouse_location', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('commodity_id_1', models.TextField(blank=True, db_column='commodity_id.1', null=True)),
                ('grade_id_1', models.TextField(blank=True, db_column='grade_id.1', null=True)),
                ('style_id', models.TextField(blank=True, null=True)),
                ('method_id', models.TextField(blank=True, null=True)),
                ('room_row_id', models.TextField(blank=True, null=True)),
                ('tag_id', models.TextField(blank=True, null=True)),
                ('region_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bin_inventory',
            },
        ),
    ]
