# Generated by Django 5.1.4 on 2024-12-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0006_bininventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bininventory',
            table=None,
        ),
    ]
