# Generated by Django 5.1.4 on 2024-12-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0007_alter_bininventory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bininventory',
            name='commodity_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='commodity_id_1',
            field=models.CharField(blank=True, db_column='commodity_id.1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='first_receive_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='grade_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='grade_id_1',
            field=models.CharField(blank=True, db_column='grade_id.1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='method_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='region_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='room_row_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='size_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='style_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='variety_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bininventory',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
