# Generated by Django 5.1.4 on 2025-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed_analysis', '0010_orders_original_ship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='filled_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
